name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - DEV
      - QA
      - PROD
  pull_request:
    branches:
      - QA
      - PROD

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Dependencies with Composer
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Unit Tests
        run: vendor/bin/phpunit

  deploy_to_qa:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/QA'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to QA
        run: ./scripts/deploy_qa.sh

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/PROD'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: ./scripts/deploy_prod.sh
